### ISSUE TITLE
[Feature] Add book editions (and format selectors) to book pages

### ISSUE THREAD

**Issue by duyfken** [nesaku/BiblioReads#10]
![Screenshot of book editions page from GoodReads](https://i.ibb.co/Dzn3b15/Screenshot-2023-06-04-at-09-15-01-Editions-of-Leviathan-Falls-by-James-S-A-Corey.png)

https://www.goodreads.com/work/editions/48382891?filter_by_format=Hardcover

**Comment by nesaku** [comment]
Hello duyfken,

Thank you for creating this issue. This feature has been added in https://github.com/nesaku/BiblioReads/commit/91782cf57e2c6b5c726c585ff5b253ef94598f05.

https://biblioreads.eu.org/work/editions/48382891-leviathan-falls

**Comment by duyfken** [comment]
Can we also show all the data points for "This edition"/"Book Edition" please? Not just format, but publish date/publisher, ISBN (helps immensely when searching between editions) and language.

**Comment by nesaku** [comment]
More details have been added to book editions in https://github.com/nesaku/BiblioReads/commit/777c59cdad5c95f2a3016147cfc8419e21180e78.
