### ISSUE TITLE
[Instance] biblioreads.privacyfucking.rocks

### ISSUE THREAD

**Issue by HeyMika** [nesaku/BiblioReads#14]
**What URL Is Your Instance Available At?**
https://biblioreads.privacyfucking.rocks/

**What Country Is Your Instance Being Hosted In?**
Germany

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
1Blu.de

**Do You Collect Any User Data?**
Only how many people visit the service, nothing more.

**Contact Details**
privacyfuckingrocks@proton.me

**Any Other Information?**
No

**Comment by nesaku** [comment]
Added, thank you for hosting an instance!
