### ISSUE TITLE
[Instance] https://biblioreads.ducks.party/

### ISSUE THREAD

**Issue by nyuuzyou** [nesaku/BiblioReads#18]
**What URL Is Your Instance Available At?**
https://biblioreads.ducks.party/

**What Country Is Your Instance Being Hosted In?**
Netherlands

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
Timeweb

**Do You Collect Any User Data?**
No

**Contact Details**
Email: hello@ducks.party
Telegram: t.me/nyuuzyou

**Any Other Information?**
Instance uptime can be checked here - https://uptime.ducks.party/status/ducks. There are no regional locks or any restrictions.

**Comment by nesaku** [comment]
Added, thank you for hosting an instance!
