### ISSUE TITLE
[Other] Upgrade to NextJS App router?

### ISSUE THREAD

**Issue by imminist** [nesaku/BiblioReads#19]
Dear nesaku,

I love your project. Do you have any plan to upgrade this project to App router?

**Comment by nesaku** [comment]
Hello imminist,

Glad you like BiblioReads and thank you for asking about this! This was something that I considered when Next.js 13 was released with support for the App router. At this point in time there are no plans to move to the App router.  Here are some of the reasons why I first decided against using the App router which I still believe are valid:

- The routing needs of BibilioReads are simple and do not require complex server side routing and/or rendering that would benefit from the App router
- The Pages route is simpler than the App router, no need to complicate something that is stable
- The Pages router file structure is more intuitive to work with compared to the App router(ex. multiple page.js files to keep track of)
- The performance benefits that could come with using the App router are minimal compared to the required to fetch data
- Moving to the App router would take some time and testing that could be better used building new features or supporting new/existing routes

I found that there were no meaningful benefits that would come with moving to the App router, but I'm always willing to reconsider if it will make BiblioReads better. Why do you think the App router should be used?
