### ISSUE TITLE
[Instance]

### ISSUE THREAD

**Issue by coochiecruise** [nesaku/BiblioReads#20]
**What URL Is Your Instance Available At?**
https://biblioreads.snine.nl/

**What Country Is Your Instance Being Hosted In?**
The Netherlands

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
Host: TransIP
CDN: Cloudflare

**Do You Collect Any User Data?**
No

**Contact Details**
ixty@snine.nl

**Any Other Information?**
x

**Comment by jackjona** [comment]
Added! Thank you for hosting.

**Comment by nesaku** [comment]
Added 👍 Thank you for hosting!
