### ISSUE TITLE
[Feature] Automatically redirect search results

### ISSUE THREAD

**Issue by Victor239** [nesaku/BiblioReads#22]
**Is your feature request related to a problem/an inconvenience? Please describe.**
I have a [search plugin installed for Goodreads](https://mycroftproject.com/install.html?id=41250&basename=goodreads&icontype=ico&name=Goodreads). For most other searches being redirected via LibRedirector I'm seamlessly redirected to a search results page on the proxy site - for BiblioReads however it can't handle the search request.

**Describe the solution/feature you'd like**
When a user attempts to go to a search result e.g. `https://www.goodreads.com/search?q=the+hobbit` then they're redirected to the appropriate proxy search result page e.g. `https://biblioreads.eu.org/search/the%20hobbit?type=books`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jackjona** [comment]
Hello Victor239,
Thank you for the feature request. The search results should now be redirected in https://github.com/nesaku/BiblioReads/commit/cf1a0aa1e77c923611cb0d4aa068c27be7d231db (v2.21.0)

**Comment by nesaku** [comment]
Hello Victor239,
Thank you for the feature request. The search results should now be redirected in https://github.com/nesaku/BiblioReads/commit/cf1a0aa1e77c923611cb0d4aa068c27be7d231db (v2.21.0)
