### ISSUE TITLE
[Instance] https://reads.nezumi.party

### ISSUE THREAD

**Issue by greyratdev** [nesaku/BiblioReads#23]
**What URL Is Your Instance Available At?**
https://reads.nezumi.party

**What Country Is Your Instance Being Hosted In?**
Italy

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
Vodafone Italia

**Do You Collect Any User Data?**
No

**Contact Details**
Email: n.bertazzo@protonmail.com

**Any Other Information?**
Self-hosted

**Comment by nesaku** [comment]
Added, thank you for hosting!
