### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [nesaku/BiblioReads#8]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `biblioreads.esmailelbob.xyz` / `biblioreads.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: ~~https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a~~ -> https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by nesaku** [comment]
Thank you for creating this issue.

After looking at: [https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a](https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a), [https://github.com/EsmailELBoBDev2/EsmailELBoBDev2/issues/1](https://github.com/EsmailELBoBDev2/EsmailELBoBDev2/issues/1), [https://codeberg.org/LibRedirect/browser_extension/issues/89#issuecomment-919797](https://codeberg.org/LibRedirect/browser_extension/issues/89#issuecomment-919797)

While I don't support @EsmailELBoBDev2's beliefs and opinions, I believe that they are free to express their beliefs and views. There is nothing wrong with the instance operated by EsmailELBoBDev2 itself and they are allowed to do what they want with their instance. However, I believe that discriminating against a specific community or group of people goes against the FOSS idea of remaining neutral and accessible to everyone. For this reason, I have decided to remove this instance for now.
