### ISSUE TITLE
New Instance: read.whateveritworks.org

### ISSUE THREAD

**Issue by xbdmHQ** [nesaku/BiblioReads#9]
**What URL Is Your Instance Available At?**
https://read.whateveritworks.org

**What Country Is Your Instance Being Hosted In?**
Germany

**What Hosting Provider Is Used? (Input Your ISP's Name If You Are Self-Hosting)**
ISP: Hetzner
CDN: Cloudflare

**Do You Collect Any User Data?**
None

**Contact Details**
support@whateveritworks.org (down for right now)

**Comment by nesaku** [comment]
Added, thanks for hosting an instance!
